version: '3.4'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "0bd7903b-f568-4894-8d72-3c1b507e5644"
    ports:
      - "1433:1433"

  patient.api:
    image: ${DOCKER_REGISTRY-}patientapi
    build:
      context: .
      dockerfile: Patient.Api/Dockerfile
    depends_on:
      - mssql
    ports:
      - "8080:8080"
